### ISSUE TITLE
branch: bikequest| route 30 stuck

### ISSUE THREAD

**Issue by prouser1234** [M1L4/QuestingDebug#25]
problem:
"[18:09:45] Position updated: Route 30 House 2 (4, 9) [OK]
[18:09:49] error: talkToNpcOnCell: could not find any NPC on the cell [2,6].
[18:09:49] Bot stopped"

there is no npc, script is always go there and stuck.

edit:
this happen with 'Master' also.

**Comment by M1L4** [comment]
- already fixed in the master
- additionally, no support/fixing for Jotho, until Kanto isn't done (which includes the merge of bikequest branch to master)
