### ISSUE TITLE
branch: master | Celadon: grunt loop

### ISSUE THREAD

**Issue by DubsCheckum** [M1L4/QuestingDebug#27]
CommitID: 8
Talks to the team rocket grunt infinitely displaying the last 3 lines in the log.
[pic](https://i.imgur.com/MU74e7o.png)

> [11:40:29 AM] You found a Great Ball!
> ...
> [11:40:56 AM] Ha! I'm blocking your path!
> [11:40:56 AM] What are you going to do about it?
> [11:40:56 AM] Nothing? That's too bad.
> repeat

**Comment by M1L4** [comment]
Reduced the log to the important parts. Also referencing your other issue #26.
Some questions though:
- Which branch did you use?
- Which level had your team?
- Any ideas what bot was trying to achieve (gym fighting?)

Unsure of what might have caused this issue atm, seems like bot skipped the celadon rocket quest. But as of why? no idea atm.

**Comment by M1L4** [comment]
I couldn't reproduce this error, created 5 accounts which all worked until earth badge badge without any problems. You still experiencing this issue?
Is it maybe related to lag? Did you try switching proxies?
