### ISSUE TITLE
branch: master| route 10

### ISSUE THREAD

**Issue by prouser1234** [M1L4/QuestingDebug#8]
stuck at route 10 

[15:46:54] Starting new quest: Rock Tunnel: (Route 9 to Lavander Town)

solution:
solving by going into rock tunnel.

**Comment by M1L4** [comment]
> [14:50:52] Position updated: Pokecenter Route 10 (9, 22) [OK]
> [14:50:57] Good afternoon, Trainer!
> [14:50:57] Welcome to Route Ten Pokemon Center.
> [14:50:57] Would you like me to heal your Pokemon?
> [14:51:00] Okay, let me take a look at those Pokemon.
> [14:51:04] There you go, take care of them!
> [14:51:04] Have a nice afternoon!
> [14:51:11] Position updated: Route 10 (18, 5) [OK]
> [14:51:19] No action executed: stopping the bot.
> [14:51:19] Bot stopped
